global:
  dependencies:
    python:
      - forge-sdk==5.0.9
      - forge-cli==5.0.10
      - cecs==5.0.2
      - services/*.py
  env:
    PROJECT_SLUG: 'mioc_ai'

    ENVIRONMENT_NAME: {{ env.ENVIRONMENT_NAME }}
    ENVIRONMENT: '{{ env.ENVIRONMENT | default("local", True) }}'
    LOG_LEVEL: INFO

    # Messaging
    PULSAR_URL: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    PULSAR_ENDPOINT_URL: http://pulsar-proxy.pulsar.svc.cluster.local

    # Databases
    MONGO_CLIENT_HOST: mongodb:27017
    MONGO_CLIENT_USERNAME: root

    POSTGRES_CLIENT_HOST: postgresql
    POSTGRES_CLIENT_PORT: '5432'
    POSTGRES_CLIENT_USERNAME: postgres

    REDIS_CLIENT_HOST: redis-master
    REDIS_CLIENT_PORT: '6379'

    BACKUP_CONTAINER_NAME: '{{ env.BACKUP_CONTAINER_NAME }}'
    BACKUPS_STORAGE_ACCOUNT_NAME: '{{ env.BACKUPS_STORAGE_ACCOUNT_NAME }}'

    # Misc
    DEFAULT_TIME_ZONE: Europe/Zagreb

  secrets:
    SENTRY_DSN: '{{ env.SENTRY_DSN }}'

    MONGO_CLIENT_CONNECTION_STRING: '{{ env.MONGO_CLIENT_CONNECTION_STRING }}'
    MONGO_CLIENT_PASSWORD: admin
    POSTGRES_CLIENT_PASSWORD: admin

    BACKUPS_STORAGE_ACCOUNT_KEY: '{{ env.BACKUPS_STORAGE_ACCOUNT_KEY }}'
    BACKUPS_ZIP_ENCRYPT: '{{ env.BACKUPS_ZIP_ENCRYPT }}'

  backups:
    mongo:
      enabled: false
      cron: 3 5,17 * * *
    postgres:
      enabled: false
      cron: 8 5,17 * * *
    redis:
      enabled: false
      cron: 13 5,17 * * *

  cecs:
    params: -e venv

  repository: nexus.vingd.net

services:
  rule-engine:
    type: java
    db:
      mongo: true
    resources:
      cpu: 500m
      memory: 650Mi
    dependencies:
      - armory
      - email-adapter
      - infobip-adapter
    env:
      ARMORY_SITE_URL: '{{ env.ARMORY_SITE_URL }}'
      PRINCIPAL_EMAIL: '{{ env.PRINCIPAL_EMAIL }}'
      SPREADSHEET_URL: '{{ env.SPREADSHEET_URL }}'

  heartbeat:
    package: heartbeat
    type: python
    version: 5.0.4
    env:
      HEARTBEAT_CYCLE: 30
    db:
      mongo: true
    dependencies:
      - rule-engine-api==5.0.9
    resources:
      cpu: 69m
      memory: 65Mi

  armory:
    type: django
    version: 5.1.1
    command:
      run: "daphne -b 0.0.0.0 armory.config.asgi:application"
    db:
      mongo: true
      postgres: true
    dependencies:
      - channels==3.0.5
      - channels-redis==3.4.1
      - django==3.2.16
      - daphne==3.0.2
      - django-environ==0.8.1
      - gunicorn==20.1.0
      - websockets==10.4
    env:
      SITE_URL: '{{ "armory." + env.get("HOST_DOMAIN", "") }}'
      INTERNAL_SITE_URL: "armory"
    resources:
      cpu: 50m
      memory: 75Mi

  email-adapter:
    type: python
    version: 5.0.2
    env:
      PROJECT_EMAIL_NAME: '{{ env.PROJECT_EMAIL_NAME }}'
      PROJECT_EMAIL_ADDRESS: '{{ env.PROJECT_EMAIL_ADDRESS }}'
      PROJECT_EMAIL_PASSWORD: '{{ env.PROJECT_EMAIL_PASSWORD }}'
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      IMAP_SERVER: imap.gmail.com
      IMAP_PORT: 993
      SMTP_USERNAME: '{{ env.SMTP_USERNAME }}'
      SMTP_PASSWORD: '{{ env.SMTP_PASSWORD }}'
    db:
      mongo: true
    resources:
      cpu: 50m
      memory: 75Mi

  gsheets-adapter:
    type: python
    version: 1.0.1
    db:
      mongo: true
    env:
      GOOGLE_CLIENT_CREDENTIALS: '{{ env.GOOGLE_CLIENT_CREDENTIALS }}'
      GOOGLE_SPREADSHEET_ID: "{{ env.GOOGLE_SPREADSHEET_ID }}"
    resources:
      cpu: 50m
      memory: 100Mi
  gpt3-adapter:
    type: python
    version: 5.0.0
    env:
      OPENAI_API_KEY: "{{env.OPENAI_API_KEY}}"
    resources:
      cpu: 81m
      memory: 130Mi

  control-panel:
    type: django
    version: 0.0.3
    https: true
    db:
      postgres: true
    image:
      static: true
    env:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: '{{ env.CONTROL_PANEL_ADMIN_PASSWORD | default("admin") }}'
      SITE_URL: '{{ "control-panel." + env.get("HOST_DOMAIN", "") }}'
      INTERNAL_SITE_URL: http://control-panel
      SECRET_KEY: KiOx1YWV1AaDdXmj6PdiFdsXi9iiGUghYskxeUxAQSAEODkB4E
      REPO: 'https://commit-bot:{{ env.COMMIT_TOKEN }}@{{ env.get("CI_REPOSITORY_URL", "").split("@")[1] }}'
      BRANCH: '{{ env.CI_COMMIT_BRANCH }}'
      DATA_HASH: '{{ file_hash("services/control_panel/configuration.yaml") }}'
    resources:
      cpu: 25m
      memory: 150Mi
  infobip-adapter:
    type: python
    exposed: true
    version: 5.2.0
    db:
      mongo: true
    command:
      run: "uvicorn infobip_adapter.service:app"
      cwd: "."
    env:
      INFOBIP_BASE_URL: "{{env.INFOBIP_BASE_URL}}"
      INFOBIP_API_KEY: "{{env.INFOBIP_API_KEY}}"
      INFOBIP_PHONE_NUMBER: "{{env.INFOBIP_PHONE_NUMBER}}"
    resources:
      cpu: 81m
      memory: 130Mi
