services:
  armory:
    https: true
  heartbeat:
    env:
      HEARTBEAT_CYCLE: 150
  rule-engine:
    env:
      JDK_JAVA_OPTIONS: -XX:MaxHeapSize=300M
  control-panel:
    https: true
    env:
      SECRET_KEY: '{{ env.CONTROL_PANEL_SECRET_KEY }}'
