com.mindsmiths.armory.event.UserConnected:
  - !GetOrCreateAgentByConnection
    connectionName: armory
    connectionField: connectionId
    agentType: agents.Moli
com.mindsmiths.armory.event.Submit:
  - !GetOrCreateAgentByConnection
    connectionName: armory
    connectionField: connectionId
    agentType: agents.Moli
com.mindsmiths.armory.event.UserDisconnected:
  - !GetOrCreateAgentByConnection
    connectionName: armory
    connectionField: connectionId
    agentType: agents.Moli
com.mindsmiths.infobipAdapter.models.InfobipReceivedMessage:
  - !GetAgentByConnection
    connectionName: infobip
    connectionField: from
